name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10
  - pandas
  - openpyxl
  - matplotlib
  - jupyterlab
  - rpy2

  # R
  - r-base
  - r-essentials
  - r-tidyverse
  - r-rhandsontable
