name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - notebook
  # R
  - r-base
  - r-essentials
  - r-tidyverse
  - r-rhandsontable
