name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - openpyxl
  - matplotlib
  - jupyterlab

  # R and RStudio dependencies
  - r-base            # pulls in R
  - r-essentials      # IRKernel + core tidyverse
  - r-tidyverse       # guarantees you have ggplot2, dplyr, etc
  - r-rhandsontable   # spreadsheet widget for R
